nodeLinker: pnp

packageExtensions:
  "@nabla/vite-plugin-eslint@*":
    dependencies:
      debug: "*"
  "@testing-library/dom@*":
    dependencies:
      eslint-import-resolver-node: "*"
  "@testing-library/react@*":
    dependencies:
      eslint-import-resolver-node: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint@*:
    dependencies:
      "@typescript-eslint/parser": "*"
  local-pkg@*:
    dependencies:
      jsdom: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  vite@*:
    dependencies:
      supports-color: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
