/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async (knex) => { 
  // Deletes ALL existing entries
  await knex('antennas').del();
  await knex('antennas').insert([
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      operational: true,
      target_id: 1,
      locked: true,
      band: "C",
      offset: 400,
      hpa: false,
      loopback: true,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      operational: true,
      target_id: 4,
      locked: true,
      band: "Ku",
      offset: 400,
      hpa: false,
      loopback: true,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      operational: true,
      target_id: 1,
      locked: true,
      band: "C",
      offset: 400,
      hpa: false,
      loopback: true,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      operational: true,
      target_id: 1,
      locked: true,
      band: "C",
      offset: 400,
      hpa: false,
      loopback: true,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      operational: true,
      target_id: 1,
      locked: true,
      band: "C",
      offset: 400,
      hpa: false,
      loopback: true,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      operational: true,
      target_id: 1,
      locked: true,
      band: "C",
      offset: 400,
      hpa: false,
      loopback: true,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      operational: true,
      target_id: 1,
      locked: true,
      band: "C",
      offset: 400,
      hpa: false,
      loopback: true,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      operational: true,
      target_id: 1,
      locked: true,
      band: "C",
      offset: 400,
      hpa: false,
      loopback: true,
    },
  ]);
};
