/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async (knex) => { 
  // Deletes ALL existing entries
  await knex('receivers').del();
  await knex('receivers').insert([
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1310,
      bandwidth: 5,
      modulation: '8QAM',
      fec: '3/4',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1320,
      bandwidth: 3,
      modulation: '8QAM',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 3,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 3,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 3,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 3,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 4,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 4,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 4,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 4,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 3,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 3,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 3,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 3,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 4,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 4,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 4,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 4,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 3,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 3,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 3,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 3,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 4,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 4,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 4,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 4,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 3,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 3,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 3,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 3,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 4,
      number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 4,
      number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 4,
      number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 4,
      number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1250,
      bandwidth: 10,
      modulation: 'BPSK',
      fec: '1/2',
    },
  ]);
};
