/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async (knex) => { 
  // Deletes ALL existing entries
  await knex('spectrum_analyzers').del();
  await knex('spectrum_analyzers').insert([
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      number: 1,
      operational: true,
      frequency: 1060,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      number: 2,
      operational: true,
      frequency: 4410,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      number: 1,
      operational: true,
      frequency: 1310,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      number: 2,
      operational: true,
      frequency: 4810,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 3,
      number: 1,
      operational: true,
      frequency: 1060,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 3,
      number: 2,
      operational: true,
      frequency: 4410,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 4,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 4,
      number: 2,
      operational: true,
      frequency: 4700,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 3,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 3,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 4,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 4,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 3,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 3,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 4,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 4,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 3,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 3,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 4,
      number: 1,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: false,
      antenna_id: 1,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 4,
      number: 2,
      operational: true,
      frequency: 1250,
      span: 50,
      trace: true,
      marker1freq: 1240,
      marker2freq: 1260,
      rf: true,
      antenna_id: 1,
    },
  ]);
};
