/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async (knex) => { 
  // Deletes ALL existing entries
  await knex('transmitters').del();
  await knex('transmitters').insert([
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1060,
      bandwidth: 10,
      power: -103,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1060,
      bandwidth: 10,
      power: -97,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1070,
      bandwidth: 10,
      power: -103,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 1,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1070,
      bandwidth: 10,
      power: -97,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1070,
      bandwidth: 10,
      power: -103,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1070,
      bandwidth: 10,
      power: -97,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 2,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 3,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 3,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 3,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 3,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 4,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 4,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 4,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 1,
      unit: 4,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 1,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 2,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 3,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 3,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 3,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 3,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 4,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 4,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 4,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 2,
      unit: 4,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 1,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 2,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 3,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 3,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 3,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 3,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 4,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 4,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 4,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 3,
      unit: 4,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 1,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 2,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 3,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 3,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 3,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 3,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 4,
      modem_number: 1,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 4,
      modem_number: 2,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 4,
      modem_number: 3,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
    {
      server_id: 1,
      team_id: 4,
      unit: 4,
      modem_number: 4,
      operational: true,
      antenna_id: 1,
      frequency: 1000,
      bandwidth: 10,
      power: -100,
      transmitting: false,
    },
  ]);
};
